### ISSUE TITLE
Doomed Shotgun Not centered for Lotans Tomb

### ISSUE THREAD

**Issue by LetMeInN0w** [swampyrad/RadTechWeaponsPack#48]
The doomed shotgun has broken frame offsets for Lotans Tomb: judgment & Lotan's Tomb: jailbreak
![Screenshot_Doom_20241101_193840](https://github.com/user-attachments/assets/622d3fcd-c697-4668-aef9-3c70014684f3)
![Screenshot_Doom_20241101_193908](https://github.com/user-attachments/assets/327ada24-9cc5-4e60-a30e-c241683790c5)
![Screenshot_Doom_20241101_193913](https://github.com/user-attachments/assets/93d5179b-62a1-478f-96c7-2ebfee80c4b0)

**Comment by swampyrad** [comment]
Yeah, that's my bad, I tried using my own sprite defs for the shotgun sprites, which didn't work with FreeDoom since its sprites are different sizes, breaking my custom offsets. It now uses the same sprites HD's Hunter uses, which seems to have fixed the problem.
